The list of test questions is on the same page as the test
izulolov/TestGuru pull request #7
Opened 2023-10-08 09:01 UTC by izulolov

2023-10-11 17:47 UTC, BubuntuClu requested changes

2023-10-11 17:47 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = find_test.questions.new
ты во второй строке находишь тест. тут ты вызываешь `find_test` второй раз.
ты разобрался как `before_action` работает?

2023-10-11 17:47 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = find_question
почему руками вызвал, а не через `before_action`?

2023-10-11 17:47 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +=begin    case test.level
ненужный код удаляй сразу, нет смысла его тащить дальше, будет только мешать

2023-10-12 17:17 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def title(question)
а это зачем? ты ведь можешь сделать `"Edit #{question.test)} Question"`

2023-10-12 17:17 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def title(question)
познай силу ассоциаций рельсовых

2023-10-12 17:17 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.find(params[:id])
дублирование кода. ты в нескольких экшенах это делаешь. и у тебя есть колбэк на поиск теста

2023-10-12 17:17 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.find(params[:id])
ты разобрался как before_action работает?

2023-10-17 16:57 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<h1><%= question_header(@question) %></h1>
что будет если это перенести в `form` паршиал?

2023-10-17 16:57 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<h1><%= question_header(@question) %></h1>
а тут кнопка назад не нужна?

по сути `edit/new` вьюхи выглядят одинаково, в них просто строка `<%= render 'form' %>`

2023-10-22 16:31 UTC, izulolov commented on app/views/questions/edit.html.erb
> +<h1><%= question_header(@question) %></h1>
1) Всё будет хорошо, перенес в паршиал форм
2) Нужна, забыл к сожалению. Сделал кнопку и перенес в форм, после этого осталось только <%= render 'form' %>

2023-10-22 16:41 UTC, merged