Lesson10
izulolov/TestGuru pull request #9
Opened 2024-04-10 09:11 UTC by izulolov

2024-04-10 16:55 UTC, BubuntuClu requested changes

2024-04-10 16:55 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:path] = request.fullpath
`:path` - что за путь? плохой нейминг ключа

2024-04-10 16:55 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :authenticate_user!
можно в каждый контроллер не добавлять, а добавить в родительский

2024-04-10 16:55 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies.delete(:path) || root_path
` с cookies.delete(:path) не понятно` - если непонятно, то зачем используешь? сделай то как понимаешь. использовал бы просто `cookies[:path]`, а при очищении пользователя чистил бы и куку

2024-04-10 16:55 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @user = current_user
ты занимаешься перекладыванием объектов. чем тебя не устраивает использовать метод `current_user` там где ты использовал `@user` до этого? надо чистить свой код(рефакторить легаси) под новые изменения, а не под легаси встраивать новые

2024-04-10 16:55 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    content_tag :p, flash[:alert]
тэк, допустим у тебя флэши могут быть не только с алерт ключом, как быть? надо все флэши выводить

2024-04-10 16:55 UTC, BubuntuClu commented on config/routes.rb
> +  #get 'sessions/new'
удаляй ненужный код

2024-04-10 16:55 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: 'Формат почты: example@guru.ru' }
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный индекс надо

2024-04-13 06:44 UTC, BubuntuClu requested changes

2024-04-13 06:44 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:request_path] = request.fullpath
сохранять путь стоит толькое если пользователь неавторизован, в других случаях он нам не нужен

2024-04-13 06:44 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    current_user.tests.push(@test)
👍

2024-04-13 06:44 UTC, BubuntuClu commented on app/views/sessions/_form.html.erb
> +    <%= flash_message(:alert) %>
так, допустим у меня 3 разных флэша. чтобы их вывести мне надо в этом месте написать три раза вызов `flash_message` с разными параметрами? звучит больно. и если добавиться новый ключ для флэш, мне надо будет пройтись по всем местам и добавить еще один вызов, а это уже звучит ненадежно

2024-04-13 06:44 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +  def flash_message(key)
этот метод за раз должен обработать все возможные флэши и вывести их

2024-04-13 06:44 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    content_tag :p, flash[key], class: 'flash-alert'
от ключа независит css-стиль? можно конечно так, но тогда все сообщения будут в стиле "ошибок", что будет путать пользователей

2024-04-13 06:44 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true,
https://github.com/izulolov/TestGuru/pull/9#discussion_r1559794717

это не поправил

2024-04-13 15:46 UTC, izulolov commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true,
Поправить замечание было очень интересно. Это я не сразу понял. В момент миграции выдавал ошибку, что одинаковые емайли уже в базе есть, пришлось удалить одинаковые емайли(пробовал удалить разом одним запросом, но не получилось). Пришлось по одному удалять))).

2024-04-13 17:50 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    render 'shared/flash' if flash.present?
а зачем отдельный рендер файла делать? отдавай из метода html прост

2024-04-15 10:27 UTC, merged